name: Publish (Minestom Repo)

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - uses: finnp/create-file-action@master
        env:
          FILE_NAME: "/home/runner/work/MinestomDataGenerator/MinestomDataGenerator/eula.txt"
          FILE_DATA: "eula=true"

      - name: Run 1.17 generators
        run: gradle generateData_1.17

      - name: Push data to data repository.
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'MinestomData'
          destination-github-username: 'Minestom'
          destination-repository-name: 'MinestomData'
          user-email: bot@minestom.net
          target-branch: 1.17
