name: Publish (Minestom Repo)

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Run 1.17 generators
        run: gradle generateData_1.17 -Peula=true

      - name: Push data to data repository.
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'MinestomData'
          destination-github-username: 'Minestom'
          destination-repository-name: 'MinestomData'
          user-name: 'Minestom Bot'
          user-email: bot@minestom.net
          commit-message: 'Update Data'
          target-branch: main